services:
  physler:
    build:
      context: ./service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ${REGISTRY}hard-physler
    ports:
      - 17002:9000
    restart: on-failure
    pids_limit: 1024
    mem_limit: 2Gb
