services:
  chains:
    build: .
    platform: linux/amd64
    image: ${REGISTRY}medium-chains
    restart: unless-stopped
    ports:
      - 17173:31337
    cpus: 1
    mem_limit: 256M
    memswap_limit: 256M
    stop_grace_period: 3s
