services:
  excess:
    build: .
    platform: linux/amd64
    image: ${REGISTRY}hard-excess
    restart: unless-stopped
    ports:
      - 17174:31337
      - 17175:31338
    cpus: 2
    mem_limit: 1G
    memswap_limit: 1G
    stop_grace_period: 3s
