services:
  villa:
    build: .
    restart: unless-stopped
    ports:
      - 17171:8080
    cpus: 1
    pids_limit: 512
    mem_limit: 256M
    memswap_limit: 256M
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    stop_grace_period: 3s
