services:
  jabba:
    build: .
    platform: linux/amd64
    image: ${REGISTRY}medium-jabba
    restart: unless-stopped
    ports:
      - 17176:7070
    cpus: 1
    mem_limit: 512M
    memswap_limit: 512M
    stop_grace_period: 3s
