[package]
name = "predictor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ydfmacro = { path = "../ydfmacro" }
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"]}
