[package]
name = "ydflib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
byteorder = "1.5.0"
prost = "0.13.3"
